# Generated by Django 3.2.4 on 2021-12-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teen_wolf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='title',
        ),
    ]
